"""Add github_stars to tools

Revision ID: 5edc3e070215
Revises: ec3de61fa90c
Create Date: 2026-01-09 18:34:32.124489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5edc3e070215'
down_revision: Union[str, None] = 'ec3de61fa90c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('github_stars', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'github_stars')
    # ### end Alembic commands ###
