"""add accessibility checker models and fields

Revision ID: af616f9e2e35
Revises: 027e859045ab
Create Date: 2026-01-11 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af616f9e2e35'
down_revision: Union[str, None] = '027e859045ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create accessibility_check_logs table
    op.create_table('accessibility_check_logs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tool_id', sa.UUID(), nullable=False),
        sa.Column('check_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('was_accessible', sa.Boolean(), nullable=False),
        sa.Column('requires_vpn', sa.Boolean(), nullable=False),
        sa.Column('response_time', sa.Float(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Create accessibility_audits table
    op.create_table('accessibility_audits',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tool_id', sa.UUID(), nullable=False),
        sa.Column('old_status', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('new_status', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('change_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('change_reason', sa.Text(), nullable=True),
        sa.Column('triggered_by', sa.String(length=100), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Add new columns to tools table
    op.add_column('tools', sa.Column('manual_override_enabled', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('tools', sa.Column('manual_override_reason', sa.Text(), nullable=True))
    op.add_column('tools', sa.Column('manual_override_set_by', sa.String(length=255), nullable=True))
    op.add_column('tools', sa.Column('manual_override_set_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tools', sa.Column('last_accessibility_check', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove columns from tools table
    op.drop_column('tools', 'last_accessibility_check')
    op.drop_column('tools', 'manual_override_set_at')
    op.drop_column('tools', 'manual_override_set_by')
    op.drop_column('tools', 'manual_override_reason')
    op.drop_column('tools', 'manual_override_enabled')

    # Drop tables
    op.drop_table('accessibility_audits')
    op.drop_table('accessibility_check_logs')

    # ### end Alembic commands ###
