"""add crawled_content table

Revision ID: ec51d405850a
Revises: 027e859045ab
Create Date: 2026-01-11 04:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec51d405850a'
down_revision: Union[str, None] = '027e859045ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawled_content',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_category', sa.String(length=100), nullable=True),
    sa.Column('suggested_pricing', sa.String(length=50), nullable=True),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawled_content_source'), 'crawled_content', ['source'], unique=False)
    op.create_index(op.f('ix_crawled_content_status'), 'crawled_content', ['status'], unique=False)
    op.create_index(op.f('ix_crawled_content_url'), 'crawled_content', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawled_content_url'), table_name='crawled_content')
    op.drop_index(op.f('ix_crawled_content_status'), table_name='crawled_content')
    op.drop_index(op.f('ix_crawled_content_source'), table_name='crawled_content')
    op.drop_table('crawled_content')
    # ### end Alembic commands ###
